"use client";

import { getVerdictColor, getVerdictBgClass } from "@/lib/types";
import type { VerdictCode } from "@/lib/types";
import { getPolygonscanUrl } from "@/lib/blockchain";

interface CertificateProps {
  verificationId: string;
  realityScore: number;
  verdict: VerdictCode;
  verdictLabel: string;
  contentHash: string;
  fileName: string;
  fileType: string;
  blockchainTxHash: string | null;
  timestamp: string;
}

export default function Certificate({
  verificationId,
  realityScore,
  verdict,
  verdictLabel,
  contentHash,
  fileName,
  fileType,
  blockchainTxHash,
  timestamp,
}: CertificateProps) {
  const color = getVerdictColor(verdict);
  const formattedDate = new Date(timestamp).toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    timeZoneName: "short",
  });

  return (
    <div className="relative mx-auto max-w-2xl">
      {/* Holographic border effect */}
      <div className="absolute -inset-[2px] rounded-2xl bg-gradient-to-r from-cyan-500 via-purple-500 to-cyan-500 opacity-75 blur-sm animate-pulse" />
      <div className="absolute -inset-[1px] rounded-2xl bg-gradient-to-r from-cyan-500 via-purple-500 to-cyan-500 opacity-50" />

      <div className="relative rounded-2xl bg-[#0c1222] p-8 md:p-10">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-500 to-purple-600">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                <polyline points="9 12 11 14 15 10" />
              </svg>
            </div>
          </div>
          <h2 className="text-2xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
            PROOF-OF-REALITY
          </h2>
          <p className="text-sm text-white/40 mt-1">Authenticity Verification Certificate</p>
        </div>

        {/* Divider */}
        <div className="h-px bg-gradient-to-r from-transparent via-white/20 to-transparent mb-8" />

        {/* Verification ID */}
        <div className="text-center mb-8">
          <p className="text-xs text-white/40 uppercase tracking-wider mb-1">Verification ID</p>
          <p className="text-xl font-mono font-bold text-white">{verificationId}</p>
        </div>

        {/* Reality Score */}
        <div className="flex justify-center mb-8">
          <div className="text-center">
            <div
              className="text-6xl font-bold tabular-nums mb-2"
              style={{ color }}
            >
              {realityScore}%
            </div>
            <div
              className={`inline-flex px-4 py-1.5 rounded-full border text-sm font-semibold ${getVerdictBgClass(verdict)}`}
            >
              {verdictLabel}
            </div>
          </div>
        </div>

        {/* Details grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
          <InfoRow label="File Name" value={fileName} />
          <InfoRow label="File Type" value={fileType.toUpperCase()} />
          <InfoRow
            label="Content Hash (SHA-256)"
            value={contentHash}
            isMono
            fullWidth
          />
          <InfoRow label="Verified At" value={formattedDate} />
          <InfoRow
            label="Blockchain"
            value={
              blockchainTxHash ? (
                <a
                  href={getPolygonscanUrl(blockchainTxHash)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-cyan-400 hover:text-cyan-300 transition-colors underline underline-offset-2"
                >
                  ✓ Verified — View on Polygonscan
                </a>
              ) : (
                <span className="text-amber-400">⏳ Pending</span>
              )
            }
          />
        </div>

        {/* Divider */}
        <div className="h-px bg-gradient-to-r from-transparent via-white/20 to-transparent mb-6" />

        {/* Footer */}
        <div className="text-center">
          <p className="text-xs text-white/30">
            This certificate was generated by the Proof-of-Reality Network.
          </p>
          <p className="text-xs text-white/30 mt-1">
            Verify this record at{" "}
            <span className="text-cyan-500/60">proof-of-reality.network/verify</span>
          </p>
        </div>
      </div>
    </div>
  );
}

function InfoRow({
  label,
  value,
  isMono = false,
  fullWidth = false,
}: {
  label: string;
  value: React.ReactNode;
  isMono?: boolean;
  fullWidth?: boolean;
}) {
  return (
    <div className={`${fullWidth ? "md:col-span-2" : ""}`}>
      <p className="text-xs text-white/40 uppercase tracking-wider mb-1">{label}</p>
      <p
        className={`text-sm text-white/80 ${isMono ? "font-mono break-all" : ""}`}
      >
        {value}
      </p>
    </div>
  );
}
